<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-BC21NU3" name="testpackage.NewTest" tests="1" failures="0" timestamp="23 Sep 2018 09:09:10 GMT" time="3.128" errors="1">
  <testcase name="test1" time="3.128" classname="testpackage.NewTest">
    <error type="org.sikuli.script.FindFailed" message="C:/Users/Pasindu/Documents/Sikuli.sikuli/chrome.png: (50x45) in S(0)[0,0 1366x768] E:Y, T:3.0">
      <![CDATA[FindFailed: C:/Users/Pasindu/Documents/Sikuli.sikuli/chrome.png: (50x45) in S(0)[0,0 1366x768] E:Y, T:3.0
  Line 2279, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2279)
at org.sikuli.script.Region.wait(Region.java:2297)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3253)
at org.sikuli.script.Region.doubleClick(Region.java:3907)
at org.sikuli.script.Region.doubleClick(Region.java:3892)
at testpackage.NewTest.test1(NewTest.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test1 -->
</testsuite> <!-- testpackage.NewTest -->
